Anzahl Meldungen pro Kategorie herausfinden

In [ ]:
import pandas as pd
import geopandas as gpd

#read data (.csv velech chli irrefüehrend wöu s isch kes csv meh sondern es pandas (= datestruktur))
meldungen_csv = gpd.read_file("data/raw/stzh.zwn_meldungen_p.json")

#check
#display(meldungen_csv)

#eine leere Spalte an meldungen_csv anfügen 
meldungen_csv["anzahl_meldungen"] = 0
#display(meldungen_csv)

#leere Spalte mit Werten füllen
for kategorie in meldungen_csv["service_code"].unique():  #dür aui kategorie düregoo
    anzahl_meldungen = meldungen_csv[meldungen_csv["service_code"] == kategorie].shape[0] #azahl zile i dere kategorie zöue

    meldungen_csv.loc[ #mäudige i neui Spalte schribe,, loc wöu select integer based on position (glaub????)
        meldungen_csv["service_code"] == kategorie, 
        "anzahl_meldungen"] = anzahl_meldungen
    
    print(f"Kategorie: {kategorie}, Anzahl Meldungen: {anzahl_meldungen}")
    
display(meldungen_csv)

Kategorie: Strasse/Trottoir/Platz, Anzahl Meldungen: 9870
Kategorie: Abfall/Sammelstelle, Anzahl Meldungen: 27339
Kategorie: Grünflächen/Spielplätze, Anzahl Meldungen: 7238
Kategorie: Beleuchtung/Uhren, Anzahl Meldungen: 5407
Kategorie: Graffiti, Anzahl Meldungen: 3759
Kategorie: Signalisation/Lichtsignal, Anzahl Meldungen: 10975
Kategorie: Brunnen/Hydranten, Anzahl Meldungen: 1289
Kategorie: VBZ/ÖV, Anzahl Meldungen: 1882
Kategorie: Allgemein, Anzahl Meldungen: 3969
Kategorie: Schädlinge, Anzahl Meldungen: 895

,objectid,service_request_id,requested_datetime,agency_sent_datetime,updated_datetime,e,n,service_code,service_name,status,userid,title,detail,media_url,interface_used,service_notice,description,url,geometry,anzahl_meldungen
0,1,1,20130314151615,20130404072505,20130412075930,2678968,1247548,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Asp,Auf dem Asphalt des Bürgersteigs hat es eine E...,,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Asp: Auf dem Asphalt des Bürgersteigs ...,https://www.zueriwieneu.ch/report/1,POINT (8.48423 47.37404),9870
1,2,2,20130314151757,20130326140505,20130412080022,2680746,1249916,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Vermessungs,Vermessungspunkt ist nicht mehr bündig mit dem...,,Web interface,Diese Reparatur wird von uns in den kommenden ...,Vermessungs: Vermessungspunkt ist nicht mehr b...,https://www.zueriwieneu.ch/report/2,POINT (8.50819 47.39512),9870
2,3,4,20130315091416,20130315095505,20130412080810,2684605,1251431,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Beim Trotto,Beim Trottoir sind einige Randsteine defekt un...,https://www.zueriwieneu.ch/photo/4.0.jpeg?bfbb...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Beim Trotto: Beim Trottoir sind einige Randste...,https://www.zueriwieneu.ch/report/4,POINT (8.55959 47.40826),9870
3,4,5,20130315091715,20130320100505,20130412080905,2681754,1250376,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Par,Auf dem Parkplatz beim Waidspital sind einige ...,https://www.zueriwieneu.ch/photo/5.0.jpeg?e309...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Par: Auf dem Parkplatz beim Waidspital...,https://www.zueriwieneu.ch/report/5,POINT (8.52163 47.39913),9870
4,5,6,20130315103653,20130422182505,20130423135033,2683094,1247762,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,16624,Arbeitskist,Arbeitskiste ist rund herum verschmiert,https://www.zueriwieneu.ch/photo/6.0.jpeg?8e65...,Web interface,Dieses Graffiti wird von uns in den kommenden ...,Arbeitskist: Arbeitskiste ist rund herum versc...,https://www.zueriwieneu.ch/report/6,POINT (8.53889 47.37545),27339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72618,72619,81200,20260501222611,20260503150206,20260503150206,2684493,1252578,Allgemein,Allgemein,confirmed,4890,Motorrad st,Motorrad steht schon seit einigen Tagen auf de...,,mobile,,Motorrad st: Motorrad steht schon seit einigen...,https://www.zueriwieneu.ch/report/81200,POINT (8.55832 47.41859),3969
72619,72620,81201,20260501233355,20260503150206,20260503150206,2682506,1244158,Allgemein,Allgemein,confirmed,15982,Hier auf de,"Hier auf dem Trottoir, wo zwar auch der Velove...",,iOS,,"Hier auf de: Hier auf dem Trottoir, wo zwar au...",https://www.zueriwieneu.ch/report/81201,POINT (8.53044 47.34312),3969
72620,72621,81203,20260502074203,20260503151205,20260503151205,2678914,1248310,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,external,7498,"Solarpanel,","Solarpanel, des Lichtsignals ist auf Kopfhöhe ...",https://www.zueriwieneu.ch/photo/81203.0.jpeg?...,Android,Freundliche Grüsse <br/> <br/> Ihre Stadt Zür...,"Solarpanel,: Solarpanel, des Lichtsignals ist ...",https://www.zueriwieneu.ch/report/81203,POINT (8.48365 47.3809),9870
72621,72622,81222,20260502124820,20260503150706,20260503150706,2683334,1252303,Allgemein,Allgemein,confirmed,290,E roller bl,E roller blockiert Trottoir. Kinderwagen und R...,https://www.zueriwieneu.ch/photo/81222.0.jpeg?...,Android,,E roller bl: E roller blockiert Trottoir. Kind...,https://www.zueriwieneu.ch/report/81222,POINT (8.54291 47.41626),3969
72622,72629,81274,20260503185227,20260503202707,20260503202707,2685959,1244857,Signalisation/Lichtsignal,Signalisation/Lichtsignal,confirmed,4839,Hallo zusam,Hallo zusammen <br/> <br/> Das Verbotsschild ...,https://www.zueriwieneu.ch/photo/81274.0.jpeg?...,iOS,,Hallo zusam: Hallo zusammen <br/> <br/> Das V...,https://www.zueriwieneu.ch/report/81274,POINT (8.57626 47.34896),10975

Anzahl Meldungen pro Kategorie und Kreis/Quartier 
- improvements: listen sortieren nach anzahl meldungen

In [ ]:
from shapely.geometry import Point
import geopandas as gpd
import pandas as pd

#read data 
quartiere_json = gpd.read_file("data/raw/stzh.adm_statistische_quartiere_v.json")
quartiere_ch = quartiere_json.to_crs(epsg = 2056)
print("Quartiere JSON:", quartiere_json.columns)
print("Quartiere CSV:", quartiere_csv.columns)

#merge quartiere json und csv um sowohl räumliche daten als auch attribute wie kname zu haben
quartiere_gdf = quartiere_json.merge(
    quartiere_csv, on = "objid", how = "left")
quartiere_gdf = quartiere_gdf.set_geometry("geometry_x") #aktive geometrie wieder definieren
quartiere_gdf = quartiere_gdf.to_crs(epsg = 2056)
print("Quartiere GDF:", quartiere_gdf.columns)

meldungen_gdf = gpd.GeoDataFrame(
    meldungen_csv,
    geometry=gpd.points_from_xy(meldungen_csv["e"], meldungen_csv["n"]),
    crs=quartiere_ch.crs)
meldungen_ch = meldungen_gdf.to_crs(epsg = 2056)

#crs prüfen
print("CRS Quartiere", quartiere_gdf.crs)
print("CRS Meldungen", meldungen_ch.crs)

#spatial join
meldungen_quartier_join = gpd.sjoin(
    meldungen_ch, #left
    quartiere_gdf, #right
    how = "inner", predicate = "intersects")
print("JOIN:", meldungen_quartier_join.columns)

meldungen_pro_quartier = (meldungen_quartier_join.groupby("qname").size().reset_index(name = "anzahl_meldungen"))
display(meldungen_pro_quartier)

meldungen_pro_kreis = (meldungen_quartier_join.groupby("kname").size().reset_index(name = "anzahl_meldungen"))
display(meldungen_pro_kreis)

Quartiere JSON: Index(['objid', 'objectid', 'geometry'], dtype='str')
Quartiere CSV: Index(['objid', 'objectid', 'qname', 'qnr', 'kname', 'knr', 'geometry'], dtype='str')
Quartiere GDF: Index(['objid', 'objectid_x', 'geometry_x', 'objectid_y', 'qname', 'qnr',
       'kname', 'knr', 'geometry_y'],
      dtype='str')
CRS Quartiere EPSG:2056
CRS Meldungen EPSG:2056
JOIN: Index(['objectid', 'service_request_id', 'requested_datetime',
       'agency_sent_datetime', 'updated_datetime', 'e', 'n', 'service_code',
       'service_name', 'status', 'userid', 'title', 'detail', 'media_url',
       'interface_used', 'service_notice', 'description', 'url', 'geometry',
       'index_right', 'objid', 'objectid_x', 'objectid_y', 'qname', 'qnr',
       'kname', 'knr', 'geometry_y'],
      dtype='str')

                   qname  anzahl_meldungen
0              Affoltern              2419
1            Albisrieden              2048
2           Alt-Wiedikon              2502
3             Altstetten              4094
4                   City              1741
5                   Enge              2756
6            Escher Wyss              1562
7               Fluntern              1254
8            Friesenberg              1415
9          Gewerbeschule              2230
10                  Hard              2855
11            Hirslanden              1380
12            Hirzenbach               854
13           Hochschulen              1415
14             Hottingen              1948
15                 Höngg              3090
16           Langstrasse              6185
17              Leimbach               632
18             Lindenhof              1125
19             Mühlebach               908
20            Oberstrass              1516
21              Oerlikon              2985
22               Rathaus              1457
23               Saatlen               676
24  Schwamendingen-Mitte              1234
25               Seebach              2622
26               Seefeld              1280
27              Sihlfeld              5235
28           Unterstrass              3594
29               Weinegg               809
30                  Werd              1529
31             Wipkingen              3304
32               Witikon              1132
33           Wollishofen              2837

       kname  anzahl_meldungen
0    Kreis 1              5738
1   Kreis 10              6394
2   Kreis 11              8026
3   Kreis 12              2764
4    Kreis 2              6225
5    Kreis 3              9152
6    Kreis 4             10569
7    Kreis 5              3792
8    Kreis 6              5110
9    Kreis 7              5714
10   Kreis 8              2997
11   Kreis 9              6142